### ISSUE TITLE
Create a quoting app for woo commerce

### ISSUE THREAD

**Issue by patrick-fls** [flagshipcompany/flagship-for-woocommerce#1]

**Comment by yi-FLS** [comment]
![capture all flagship shipping 100116](https://cloud.githubusercontent.com/assets/5373898/19041667/f2f1d866-8956-11e6-8339-654aa9db25eb.png)
![capture all flagship shipping 100116](https://cloud.githubusercontent.com/assets/5373898/19041682/fa13c97e-8956-11e6-8907-df3f6728c1d1.png)
![screen shot 2016-09-30 at 2 46 36 pm](https://cloud.githubusercontent.com/assets/5373898/19042054/8bcdcecc-8958-11e6-86d2-ca76ba87e4af.png)
![screen shot 2016-10-03 at 11 00 58 am](https://cloud.githubusercontent.com/assets/5373898/19042098/bbaabd94-8958-11e6-89d3-7aad04ded212.png)
