### ISSUE TITLE
Add a setting to let the customer choose from a list of service level.

### ISSUE THREAD

**Issue by dlaramee** [flagshipcompany/flagship-for-woocommerce#13]
By choosing a service level, Next Business Day, before X AM, Ground, etc... instead of all courrier and service, we'd have a smaller list of choice with best rate per service level. I think most customer don't care who the carrier is, they are usually looking for the best rate for a specific service level.

**Comment by yi-FLS** [comment]
Thank you for providing valuable feedback. Filter rates by service type is definitely something interesting to consider.  Meanwhile, there is an option in the settings, namely "Offer Rates", that allows store owner to filter rates by cost.
