### ISSUE TITLE
URGENT! Plugin missing component!

### ISSUE THREAD

**Issue by shadescolour** [flagshipcompany/flagship-for-woocommerce#23]
After installing your update, I receive this on my admin dashboard.

Plugin could not be activated because it triggered a fatal error.
Fatal error: Class '\FS\Components\Hook\MetaBoxActions' not found in /srv/users/wholesale/apps/wholesale/public/wp-content/plugins/flagship-for-woocommerce-1.0.0/src/Components/Factory/ComponentFactory.php on line 11

Thoughts?

**Comment by yi-FLS** [comment]
@shadescolour can you provide your woocommerce version?

**Comment by shadescolour** [comment]
We’ll just save some time, here’s the WooCommerce System Status Report.
Thanks for being right no this. :)

`
### WordPress Environment ###

Home URL: https://wholesale.satyatea.com
Site URL: https://wholesale.satyatea.com
WC Version: 2.6.4
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.18 (Unix) OpenSSL/1.0.1f
PHP Version: 5.6.26
PHP Post Max Size: 1 GB
PHP Time Limit: 0
PHP Max Input Vars: 5000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.5.52
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (56) ###

Gravity Forms: by rocketgenius – 2.0.7
Admin Menu Editor: by Janis Elsts – 1.7.2
Payment Gateway Based Fees and Discounts for WooCommerce: by Algoritmika Ltd – 2.1.0
WooCommerce Customer Relationship Manager: by Actuality Extensions – 2.6.11
Disable New User Notification: by RocaPress – 1.1
Flagship WooCommerce Shipping: by FlagShip Courier Solution – 0.1.12
Font Awesome Icons: by Rachel Baker – 3.2.1
Google Analytics Dashboard for WP: by Alin Marcu – 4.9.3.2
Gravity Forms No CAPTCHA reCAPTCHA: by John Parks - Folkhack Studios – 1.0.7
Gravity Forms User Registration Add-On: by rocketgenius – 3.3.9
Groups WooCommerce: by itthinx – 1.9.6
Groups: by itthinx – 1.13.1
Hide Title: by Brandon Kraft & Randall Runnels – 1.0.4
Nav Menu Roles: by Kathy Darling – 1.8.3
PHP Code For Posts: by Jamie Fraser – 2.1.3.1
Postman SMTP: by Jason Hendriks – 1.7.2
Quick Page/Post Redirect Plugin: by anadnet – 5.1.8
Shadowbox JS: by Matt Martz – 3.0.3.10.2
Simple Custom CSS: by John Regan
Danny Van Kooten – 3.3

Simple Widget Classes: by Mark Wilkinson – 0.3
Theme Check: by Otto42
pross – 20160523.1

UberMenu 3 - The Ultimate WordPress Mega Menu: by Chris Mavricos
SevenSpark – 3.1.0.1

Widget Logic: by Alan Trewartha – 0.57
WooCommerce Payment Gateway Based Fees: by WooThemes – 2.2.16
WooCommerce Advanced Free Shipping: by Jeroen Sormani – 1.0.11
WooCommerce Advanced Notifications: by WooThemes – 1.2.0
WooCommerce Extended Coupon Features: by Jos Koenis – 2.3.6
WooCommerce Cart Reports: by WPBackOffice – 1.1.9
WooCommerce Catalog Visibility Options: by Lucas Stark – 2.8.1
WooCommerce Conditional Shipping and Payments: by WooThemes – 1.2.1
WooCommerce Distance Rate Shipping: by Gerhard Potgieter – 1.0.4
WooCommerce Stripe Gateway: by Automattic – 3.0.5
WooCommerce Google Analytics Pro: by WooThemes / SkyVerge – 1.1.4
WooCommerce Jetpack Plus: by Algoritmika Ltd – 1.0.4
Booster for WooCommerce: by Algoritmika Ltd – 2.5.6
WooCommerce Order Status Manager: by WooThemes / SkyVerge – 1.6.2
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.5.37
WooCommerce Product CSV Import Suite: by Automattic – 1.10.11
WooCommerce Sequential Order Numbers Pro: by WooThemes / SkyVerge – 1.10.0
WooCommerce Shipment Tracking: by WooThemes – 1.6.0
WooCommerce Canada Post: by WooThemes – 2.4.4
WooCommerce FedEx Shipping: by WooThemes – 3.3.7
WooCommerce UPS Shipping: by WooThemes – 3.1.3
WooCommerce Shop as Customer: by cxThemes – 2.02
WooCommerce Smart Coupons: by WooThemes – 3.1.7
WooCommerce Store Credit: by WooThemes – 2.1.5
WooCommerce Tab Manager: by WooThemes / SkyVerge – 1.7.2
WooCommerce Table Rate Shipping: by Automattic – 3.0.2
WooCommerce Waitlist: by Neil Pie – 1.4.13
WooCommerce: by WooThemes – 2.6.4
WooCommerce Helper: by WooCommerce – 1.7.1
WordPress HTTPS: by Mike Ems – 3.3.6
Yoast SEO: by Team Yoast – 3.6
WP-Optimize: by Ruhani Rabin – 1.9.1
WPFront User Role Editor: by Syam Mohan – 2.12.4
YITH WooCommerce Customize My Account Page: by YITHEMES – 1.1.1

### Settings ###

Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /shop
Cart: #5 - /cart
Checkout: #6 - /checkout
My Account: #7 - /my-account

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Bazar Child
Version: 3.0.1
Author URL: http://yithemes.com
Child Theme: ✔
Parent Theme Name: Bazar
Parent Theme Version: 3.0.1
Parent Theme Author URL: http://yithemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: bazar/woocommerce/archive-product.php
bazar/woocommerce/cart/cart-empty.php
bazar/woocommerce/cart/cart-shipping.php
bazar/woocommerce/cart/cart-totals.php
bazar/woocommerce/cart/cart.php
bazar/woocommerce/cart/cross-sells.php
bazar/woocommerce/cart/mini-cart.php
bazar/woocommerce/cart/shipping-calculator.php
bazar/woocommerce/checkout/cart-errors.php
bazar/woocommerce/checkout/form-billing.php
bazar/woocommerce/checkout/form-checkout.php
bazar/woocommerce/checkout/form-coupon.php
bazar/woocommerce/checkout/form-login.php
bazar/woocommerce/checkout/form-shipping.php
bazar/woocommerce/checkout/review-order.php
bazar/woocommerce/checkout/thankyou.php
bazar-child/woocommerce/content-product.php version 2.5.0 is out of date. The core version is 2.6.1
bazar/woocommerce/content-product_cat.php
bazar/woocommerce/content-single-product.php
bazar/woocommerce/global/form-login.php
bazar/woocommerce/global/sidebar.php
bazar/woocommerce/global/wrapper-end.php
bazar-child/woocommerce/global/wrapper-start.php
bazar/woocommerce/loop/add-to-cart.php
bazar/woocommerce/loop/no-products-found.php
bazar/woocommerce/loop/pagination.php
bazar/woocommerce/loop/price.php
bazar/woocommerce/loop/sale-flash.php
bazar/woocommerce/single-product/add-to-cart/external.php
bazar/woocommerce/single-product/add-to-cart/grouped.php
bazar/woocommerce/single-product/add-to-cart/simple.php
bazar/woocommerce/single-product/add-to-cart/variable.php
bazar/woocommerce/single-product/price.php
bazar/woocommerce/single-product/product-image.php version 2.0.14 is out of date. The core version is 2.6.3
bazar/woocommerce/single-product/product-thumbnails.php version 2.3.0 is out of date. The core version is 2.6.3
bazar/woocommerce/single-product/rating.php
bazar/woocommerce/single-product/related.php
bazar/woocommerce/single-product/sale-flash.php
bazar/woocommerce/single-product/short-description.php
bazar/woocommerce/single-product/tabs/description.php
bazar/woocommerce/single-product/tabs/tabs.php
bazar-child/woocommerce/single-product/title.php
bazar/woocommerce/single-product/up-sells.php
bazar/woocommerce/single-product-reviews.php
bazar/woocommerce/single-product.php



--
ShadesColour & Associates
info@shadescolour.com

http://www.shadescolour.com

https://www.facebook.com/ <https://www.facebook.com/satyateaco>shadescolour
https://www.twitter.com/ <https://www.twitter.com/satyatea>shadescolour
https://www.pinterest.com/ <https://www.pinterest.com/satyatea>shadescolour

**Comment by yi-FLS** [comment]
@shadescolour thanks for your valuable feedback. just rolling out v1.0.1, check it out! =)

**Comment by shadescolour** [comment]
Now settings are blank.
It leads to nothing!

--
ShadesColour & Associates
info@shadescolour.com

http://www.shadescolour.com

https://www.facebook.com/ <https://www.facebook.com/satyateaco>shadescolour
https://www.twitter.com/ <https://www.twitter.com/satyatea>shadescolour
https://www.pinterest.com/ <https://www.pinterest.com/satyatea>shadescolour

**Comment by shadescolour** [comment]
but it does turn on.

**Comment by yi-FLS** [comment]
@shadescolour 
- WooCommerce 2.6 Shipping are now in favor of shipping zones. From WC perspective, you might and should define shipping method's setting per shipping zones. This plugin do not pre-load any existing settings. 
- Non-shipping zone global settings is still available (given they've ever set) from WC Settings -> Shipping -> FlagShip Shipping
- It is recommend to have global settings filled for backwards compatiblity purpose

**Comment by shadescolour** [comment]
In the clip I attached do you see: WC Settings -> Shipping -> FlagShip Shipping anywhere?

--
ShadesColour & Associates
info@shadescolour.com

http://www.shadescolour.com

https://www.facebook.com/ <https://www.facebook.com/satyateaco>shadescolour
https://www.twitter.com/ <https://www.twitter.com/satyatea>shadescolour
https://www.pinterest.com/ <https://www.pinterest.com/satyatea>shadescolour

**Comment by yi-FLS** [comment]
@shadescolour 
- can you try the following link? YOUR_SITE_URL/wp-admin/admin.php?page=wc-settings&tab=shipping&section=flagship_shipping_method

**Comment by shadescolour** [comment]
Yes,
That is what the screenshot was from. :)

--
ShadesColour and Associates
info@shadescolour.com

http://www.shadescolour.com

https://www.facebook.com/shadescolour
https://www.twitter.com/shadescolour

**Comment by shadescolour** [comment]
So, same answer.
Still no shipping options.

Please let me know if you figure this out, I’m going to revert back to the plugin version that works for now.

--
ShadesColour & Associates
info@shadescolour.com

http://www.shadescolour.com

https://www.facebook.com/ <https://www.facebook.com/satyateaco>shadescolour
https://www.twitter.com/ <https://www.twitter.com/satyatea>shadescolour
https://www.pinterest.com/ <https://www.pinterest.com/satyatea>shadescolour

**Comment by yi-FLS** [comment]
@shadescolour 
- so far,  I wouldn't be able to reproduce the bug through neither upgrade nor clean installation. 
- by simple curiousity, the summary report you attached some hours  ago mentioned the plugin version you used is v0.1.12.  Can you confirmed that "missing options" page occured on v1.0?

**Comment by shadescolour** [comment]
At that point I had switched the plugin back.
Then you updated it again and I retried with the new update and the second error occurred, so I switched back to the old version of the plugin again.

It was with the correct version when I took the screenshot. 

--
ShadesColour and Associates
info@shadescolour.com

http://www.shadescolour.com

https://www.facebook.com/shadescolour
https://www.twitter.com/shadescolour

**Comment by docuhub** [comment]
Same issue here.  After upgrading the plugin to 1.01 I have lost Flagship as a shipping option.  Same screen capture as @shadescolour.  Do we need to switch back to an earlier version or is the fix almost ready?

**Comment by yi-FLS** [comment]
@shadescolour @docuhub at the moment, we are still working on the fix. For production, I would recommend to rollback to previously working version.

**Comment by yi-FLS** [comment]
@shadescolour @docuhub 
problem seems to occur only on linux hosting servers. a patch has been made to address the issue.

**Comment by shadescolour** [comment]
Hi,
Yes the settings appear to be showing again, but now the plugin is not actually outputting shipping quotes... can you please look into that?

Thanks.

--
ShadesColour and Associates
info@shadescolour.com

http://www.shadescolour.com

https://www.facebook.com/shadescolour
https://www.twitter.com/shadescolour

**Comment by yi-FLS** [comment]
@shadescolour 
- You need to fill the shipping settings for each of the shipping zones that has FlagShip Shipping enabled. Please check the readme. Detailed screenshot are included.
