### ISSUE TITLE
Does it automatically schedule pickups?

### ISSUE THREAD

**Issue by pwagz** [flagshipcompany/flagship-for-woocommerce#26]
I want to ensure we have control over what pickups are scheduled and when. Does this plugin automatically create the pick-ups with couriers or are they created manually only? I don't see any options for this in the settings.

**Comment by dlaramee** [comment]
You control the printing of the label and the pickup scheduling from the order management. You can re-quote and/or choose another carrier from there and set few pickup settings like insurance, signature, reference, etc...

**Comment by pwagz** [comment]
Thank you. I saw in the options it had settings regarding pick ups so I wanted to be sure but was unable to test it on the environment it's installed in. Much appreciated.
