### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by shadescolour** [flagshipcompany/flagship-for-woocommerce#30]
Hi, when I enable v.2.0.0 the following error appears: Notice: Undefined index: enabled in /www/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-shipping-method.php on line 439
Thoughts?

**Comment by shadescolour** [comment]
And these!

Notice: Undefined variable: store in /www/wp-content/plugins/flagship-for-woocommerce-2.0.0/src/Components/Alert/Scenario/Native.php on line 13

Notice: Undefined index: TEXT_DOMAIN in /www/wp-content/plugins/flagship-for-woocommerce-2.0.0/src/Injection/I.php on line 169

**Comment by luis709394** [comment]
We'll have a look at those, thanks!

**Comment by luis709394** [comment]
Hi, we just made a release (v.2.0.1)  that will fix all the bugs you described. Please install it and see how it works this time.
