### ISSUE TITLE
Ability to change unit type from Imperial to Metric 

### ISSUE THREAD

**Issue by makemagik** [flagshipcompany/flagship-for-woocommerce#40]
It would be nice to have the ability to change the unit type. My client use metric units for all his product.

There's only 4 files containing the keyword "imperial" so it should be an easy trick. I might try to do the change and make a pull request out of it.

Thanks for the plugin

**Comment by luis709394** [comment]
This is a very good suggestion.

**Comment by luis709394** [comment]
Hi makeMagik,

After reviewing the code related to this issue, I am not sure what exactly the need is. The plugin takes the dimensions of products. If the product dimensions are in metric, they will be converted to imperial and sent to the Flagship Shipping API. So metric dimensions still work.
