### ISSUE TITLE
If address is changed, rates are not updated.

### ISSUE THREAD

**Issue by Suprazz** [flagshipcompany/flagship-for-woocommerce#41]
Let says I try one shipping address and get rates. It work well. Then I want to get rates to another address, the shipping rates stays the same.

Even if I process the order, rates are not updated at all.

**Comment by luis709394** [comment]
Hi,

Where did you change the shipping address? from the cart page and change in "calculate shipping"? I tried it and every time I changed the postal code the rates got updated. On the checkout page, the postal code could be from the browser cache sometimes, so when you update the postal code on the cart page and proceed to checkout the checkout page might still have the old postal code. Could you open up a browser window in private code every time to see rates change when postal code changes (better with very different locations) ?

**Comment by Suprazz** [comment]
Hi, Thanks for the fast answer.
I tried the shipping calculator in the cart directly.
If I open a new private window it updates one time and then it stops updating. 
I tried with chrome and firefox.
Tried with updating address within Canada only and USA only and switching between USA and Canada.

**Comment by luis709394** [comment]
But I am not able to reproduce the issue on my end. Could you check your woocommerce settings? The way it caches the postal code and rates has nothing to do with the shipping plugin.

**Comment by Suprazz** [comment]
Are you available for a team viewer session? contact me a samuel at perfecttuning dot net

**Comment by patrick-fls** [comment]
Can you please submit your WooCommerce status? WooCommerce -> Status -> Get System Report

**Comment by Suprazz** [comment]
`
### WordPress Environment ###

Home URL: http://192.168.2.192
Site URL: http://192.168.2.192
WC Version: 3.3.4
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.28
PHP Post Max Size: 40 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.2o

SUHOSIN Installed: –
MySQL Version: 5.7.21
Max Upload Size: 40 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 2.91MB
Database Data Size: 2.07MB
Database Index Size: 0.84MB
wp_woocommerce_sessions: Data: 0.11MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.08MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.44MB + Index: 0.02MB
wp_postmeta: Data: 0.02MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

customize_changeset: 1
page: 7
post: 2
product: 1
shop_order: 1

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (5) ###

Flagship WooCommerce Shipping: by Flagship Courier Solution – 0.1.6 – Not tested with the active version of WooCommerce
Jetpack by WordPress.com: by Automattic – 6.0
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.5.1
WooCommerce Services: by Automattic – 1.12.3
WooCommerce: by Automattic – 3.3.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.2.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by luis709394** [comment]
Looks like you are using a deprecated version of our plugin:

```Flagship WooCommerce Shipping: by Flagship Courier Solution – 0.1.6 – Not tested with the active ```

Please download the latest version,which is 2.0.8

**Comment by Suprazz** [comment]
Ok I did that!
Now I have this message: by FlagShip Courier Solution – 2.0.8 – Not tested with the active version of WooCommerce (my WC version is the latest one 3.3.4).

And rate doesn’t appear at all now. 
So I tried again from scratch, created a new tocken and the rates doesn’t appear at all now when I click on "Calculate shipping"

**Comment by Suprazz** [comment]
OK I did that. Reconfigured everything and it work well! :) Thanks guys for the support!
