### ISSUE TITLE
Cannot disable specific carriers

### ISSUE THREAD

**Issue by bing-bing-bing-bing** [flagshipcompany/flagship-for-woocommerce#47]
Hi guys,

I have the checkboxes selected for disabling UPS, Fedex, DHL and Canpar in the settings of the only shipping zone I have.

Unfortunately, they are still shown on the client side.

Do you have any idea why?

**Comment by luis709394** [comment]
Yes, there is a problem of filtering out rates from certain couriers.
We are fixing this issue and will include it in our next release (should be in the new few days).
Sorry about this and thanks for letting us know!

**Comment by luis709394** [comment]
Hi,
This issue should be fixed in the latest release, 2.0.10. Please install to see if it works.
