### ISSUE TITLE
FlagShip API Error:  Flagship Shipping has some difficulty in retrieving the rates. Please contact site administrator for assistance.

### ISSUE THREAD

**Issue by philraymond** [flagshipcompany/flagship-for-woocommerce#48]
I'm getting this error:

![screen shot 2018-11-04 at 8 58 23 pm](https://user-images.githubusercontent.com/44759598/47973821-6d564a80-e074-11e8-8c59-142864cfa6f8.png)

I've entered my Access Token and I believe I have everything set up properly:

![screen shot 2018-11-04 at 9 06 08 pm](https://user-images.githubusercontent.com/44759598/47974024-7e538b80-e075-11e8-8490-ef65e61cf408.png)

![screen shot 2018-11-04 at 8 59 38 pm](https://user-images.githubusercontent.com/44759598/47973862-9a0a6200-e074-11e8-9f19-21643d58df91.png)

Any ideas?

**Comment by luis709394** [comment]
It is really hard to tell only from the screen. First, make sure the token is not a test token. It has to be a valid one for production. You have to have a enabled FlagShip account to generate a valid token. If your token is valid but the plugin still does not work, you can contact the FlagShip customer service and we will try to find out the reason.

**Comment by birkoss** [comment]
We are having the same issue.

We can however get rates in the frontend. 

In the backend, if we click on Get an estimate (and then, click on Update to update the order), we are having the same error as the OP.

Also, in the plugins settings (we changed the key to be sure it wasnt key related), it loads indefinitely. If we reload the page, the new key is saved.

Any clues on how to debug this?

**Comment by luis709394** [comment]
@birkoss ,

Did you try with the latest release 2.0.10? Let me know if the same issue happens with 2.0.10. Thanks!

**Comment by birkoss** [comment]
@luis709394 

2.0.10 fixed the infinite loading while saving the settings.

This message error still happen when I click on UPDATE order (which is disabled when I click on get estimates) : https://screencast.com/t/OIZdCGUfuzJ

Any other ideas?

Thanks

**Comment by luis709394** [comment]
The plugin should do nothing when "update order" is clicked. The error you showed normally happens when the API token is invalid. Can you check the API token?
