### ISSUE TITLE
Error message: FlagShip API token missing but API token is in place

### ISSUE THREAD

**Issue by bing-bing-bing-bing** [flagshipcompany/flagship-for-woocommerce#50]
Everything was working fine using version 2.0.11 since it's release, but this week, when we go to an order in the admin section and click on "Export to FlagShip", we get the error message "FlagShip API token missing. Please create a FlagShip API token and save in the plugin settings.".

The API key is in place and the front-end is still working, pulling shipping rates correctly from Flagship.

We tried rotating the key, but it's still giving us the same message.

Any advice?

**Comment by luis709394** [comment]
Hi, I cannot reproduce the issue on my end. The front-end is using the token saved in the settings for shipping zones, whilst the backend is using the token saved in the plugin global settings. Looks like in your case the global settings have token missing but it is there for shipping zones. Did you put the token into the plugin settings and save. Once the settings are saved each shipping zone will have the same token as the global settings. Please take notice of the notification message at top after you click save. If there is a message like "Shipping Integrity Failure", it could mean the token is invalid. 

Please let us know if the problem persists.

**Comment by bing-bing-bing-bing** [comment]
Hi Luis,

Yes, I did save the token in the plugin settings.  There is no error message when I save it.  Just a confirmation settings were saved.

![image](https://user-images.githubusercontent.com/1617610/54229485-bdd62c80-44da-11e9-8c57-2173bda6fff1.png)

**Comment by luis709394** [comment]
It is very difficult to know what is going on your end. Do you have an older version of Flagship plugin installed and still not deleted? It might be better that you contact the customer service directly: support@flagshipcompany.com, 1-866-320-8383. They will help you debug.
