### ISSUE TITLE
Shipping Cost Markup per package box

### ISSUE THREAD

**Issue by Red-Cross-Knight** [flagshipcompany/flagship-for-woocommerce#52]
Add ability to set specific shipping cost mark up per box size as defined in "FlagShip Shipping" configuration under Package Box.

**Comment by luis709394** [comment]
Hi, can you explain more on 'cost mark up per box size' ? Is that once the box size exceeds certain value, there will be an automatic markup applied to the shipping rate?

**Comment by Red-Cross-Knight** [comment]
Hey Junfeng,

Sorry for the late repl, your email ended up in our other folder.

See if i can explain this in a better way.

Currently, we're able to set the Markup in the Shipping Settings on all
boxes ( Shipping Cost Markup Type / Shipping Cost Markup).

What we would like would be to set this markup value being able to be
defined under Parcel / Packaging and applied to the quote.  This could be
by adding a new column to the the Package Box section.

IE:

Model Name

Length (in)

Width (in)

Height (in)

Max Supported (lb)

Box Markup

Box 1

8

8

8

20

$5.00

Box 2

12

12

12

30

$10.00

Box 3

14

14

14

40

$15.00

Does that make sense?

Thanks
-Ben

**Comment by luis709394** [comment]
Yes, completely makes sense! That is markup per box model. We will take time to add this feature. If it works well, we will include it in our next release. Thanks again for the good suggestion!
