### ISSUE TITLE
Smart packaging for weight limitation

### ISSUE THREAD

**Issue by Elhadj144** [flagshipcompany/flagship-for-woocommerce#53]
If packaging in one box gets heavy (more than 150 lbs), automatically split the boxes to have multiple packages instead.

**Comment by luis709394** [comment]
The question is how do we split? A package can have dimensions of 40*40*40, with weight of 160 lbs, but actually there are two items inside, one is 40*40*30, weight 90 lbs, and the other is 40*40*10, weight 70 lbs. But we have no information about the dimensions and weights of the items inside. In an extreme case, if a very large and heavy item is inside (maybe a computer desk), it is impossible to split ........

**Comment by luis709394** [comment]
Actually, the "Box Split" setting can already handle this situation.
