### ISSUE TITLE
Add customer email address to tracking field

### ISSUE THREAD

**Issue by Red-Cross-Knight** [flagshipcompany/flagship-for-woocommerce#58]
On order export to Flagship all user information is transfered except for user email address which would go into Tracking Emails field on the website.

**Comment by luis709394** [comment]
In fact, there is an option in the shipping zone settings that enables the tracking email to the customer. To enable it, just go to the FlagShip settings under a shipping zone, check the box of "Send tracking updates to billing email".
It looks like this:
![Screenshot from 2020-02-17 09-50-31](https://user-images.githubusercontent.com/8826928/74664566-fa3eed80-516b-11ea-8c41-ab505e853184.png)

**Comment by Red-Cross-Knight** [comment]
Have that enabled, but due to some other requirements have to do quotes manually via 'export to flagship' button which doesn't export the billing email address.

**Comment by luis709394** [comment]
We just tested with a manually created order. You are right. It does not work for manually created orders. We will figure out a solution and include the fix in our next release. Thanks for finding this bug for us!

**Comment by Red-Cross-Knight** [comment]
No problem, happy to find them if they make our lives easier in the long run ;)
