### ISSUE TITLE
API Errors - Keep visable

### ISSUE THREAD

**Issue by Red-Cross-Knight** [flagshipcompany/flagship-for-woocommerce#60]
Occasionally when an order is manually submitted the API throughs an error, however this only shows for approx 2 seconds before it automatically closes.  

Recommend to leave open so error can be read.

**Comment by Red-Cross-Knight** [comment]
This seems to be fixed now? Error is shown above order screen.

**Comment by luis709394** [comment]
We have never seen the issue you mentioned. But as we just tested, the API errors stay at the top of the order page.

**Comment by Red-Cross-Knight** [comment]
Seems to be working now, but also moved location of the error, used to be in the right side "Flag Ship Menu" on order page, now shows up above the order when there is an error, maybe glitch with something else.  
![image](https://user-images.githubusercontent.com/1887734/79255988-4305e080-7e55-11ea-9883-21cc16a3c52b.png)


In either case, this can be closed.
