### ISSUE TITLE
API - Address too long

### ISSUE THREAD

**Issue by Red-Cross-Knight** [flagshipcompany/flagship-for-woocommerce#61]
Ship to allot of addresses in Quebec, which have longer names.  (ie 123 rue georges-édouard-tremblay) API gives error on address being too long, 

Address work fine when done manually on website

**Comment by luis709394** [comment]
It is strange that it can work on the FlagShip website with a long address like this one, as both the plugin and the website call the same API server. The reason for such a length restriction is that couriers have their own restrictions on the length of street address. We will try to find a solution to work around this issue. At the same time maybe you can try a shortened version of the street address so it will be accepted.

**Comment by Red-Cross-Knight** [comment]
Typically we can get away with just shortening it, and it mainly seems to be a problem with Quebec addresses.  ie today: 
address
### rue georges-édouard-tremblay This value is too long. It should have 30 characters or less.

But if I paste it into the website works fine.

**Comment by radua** [comment]
@Red-Cross-Knight It works on the website because it automatically gets trimmed
![image](https://user-images.githubusercontent.com/14368934/90057682-bf4aec00-dcae-11ea-8991-531927f185ad.png)

**Comment by Red-Cross-Knight** [comment]
Was this fixed or just closed?

**Comment by radua** [comment]
@Red-Cross-Knight Apologies. The issue was closed accidentally. Our team will fix this and inform you asap.
