### ISSUE TITLE
Shipping Class column

### ISSUE THREAD

**Issue by Red-Cross-Knight** [flagshipcompany/flagship-for-woocommerce#67]
What input method is expected for this colum? Expected a drop down or similar that would pull from woocommerce shipping class, but seems to accept any type of input.
![image](https://user-images.githubusercontent.com/1887734/89946226-99f7a880-dbf0-11ea-8830-183ef1b3782b.png)

**Comment by radua** [comment]
@Red-Cross-Knight We have updated the plugin to address this issue. Please update to version 2.0.19.

**Comment by Red-Cross-Knight** [comment]
Fix does not seem to be working? 

Versons: 
Wordpress - 5.3.4
WooCommerce - 3.9.2
Flagship - 2.0.19

**Comment by radua** [comment]
Hello Red-Cross-Knight,
It is working for me.

![image](https://user-images.githubusercontent.com/14368934/90154631-591aa380-dd58-11ea-8861-26c29c0599bf.png)

![image](https://user-images.githubusercontent.com/14368934/90155534-7308b600-dd59-11ea-80ac-6a3250176570.png)

**Comment by Red-Cross-Knight** [comment]
Unsual, what version of wordpress and woocommerce?

**Comment by Red-Cross-Knight** [comment]
Found a work around, have to re-create all our box sizes.  Once I select to add a new box I get the drop down.

 Doesn't show on existing boxes.  

And it is not possible to modify once selected, without deleting and recreating. 

![image](https://user-images.githubusercontent.com/1887734/90162822-38a41680-dd63-11ea-9506-d4bc0b8a231e.png)
