### ISSUE TITLE
v3.0 install

### ISSUE THREAD

**Issue by Red-Cross-Knight** [flagshipcompany/flagship-for-woocommerce#70]
Updated to v3.0 using woocommerce update.  

Looking at the error + actual directory seems the /includes directory wasnt installed? 

Warning: include_once(/home/testing/public_html/wp-content/plugins/flagship-woocommerce-shipping/includes/UserFunctions.php): failed to open stream: No such file or directory in /home/testing/public_html/wp-content/plugins/flagship-woocommerce-shipping/flagship-for-woocommerce.php on line 31

Warning: include_once(): Failed opening '/home/testing/public_html/wp-content/plugins/flagship-woocommerce-shipping/includes/UserFunctions.php' for inclusion (include_path='.:/opt/alt/php72/usr/share/pear') in /home/testing/public_html/wp-content/plugins/flagship-woocommerce-shipping/flagship-for-woocommerce.php on line 31

Warning: include_once(includes/FlagshipWoocommerceShipping.php): failed to open stream: No such file or directory in /home/testing/public_html/wp-content/plugins/flagship-woocommerce-shipping/flagship-for-woocommerce.php on line 43

Warning: include_once(): Failed opening 'includes/FlagshipWoocommerceShipping.php' for inclusion (include_path='.:/opt/alt/php72/usr/share/pear') in /home/testing/public_html/wp-content/plugins/flagship-woocommerce-shipping/flagship-for-woocommerce.php on line 43

Fatal error: Uncaught Error: Class 'FlagshipWoocommerce\FlagshipWoocommerceShipping' not found in /home/testing/public_html/wp-content/plugins/flagship-woocommerce-shipping/flagship-for-woocommerce.php:47 Stack trace: #0 /home/testing/public_html/wp-settings.php(377): include_once() #1 /home/testing/public_html/wp-config.php(78): require_once('/home/testing/...') #2 /home/testing/public_html/wp-load.php(37): require_once('/home/testing/...') #3 /home/testing/public_html/wp-admin/admin.php(34): require_once('/home/testing/...') #4 /home/testing/public_html/wp-admin/index.php(10): require_once('/home/testing/...') #5 {main} thrown in /home/testing/public_html/wp-content/plugins/flagship-woocommerce-shipping/flagship-for-woocommerce.php on line 47
There has been a critical error on your website. Please check your site admin email inbox for instructions.

**Comment by redfishstix** [comment]
Same thing here!

Warning: include_once(/wp-content/plugins/flagship-for-woocommerce-2.0.17/includes/UserFunctions.php): failed to open stream: No such file or directory in /wp-content/plugins/flagship-for-woocommerce-2.0.17/flagship-for-woocommerce.php on line 31

Warning: include_once(): Failed opening '/wp-content/plugins/flagship-for-woocommerce-2.0.17/includes/UserFunctions.php' for inclusion (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') in /wp-content/plugins/flagship-for-woocommerce-2.0.17/flagship-for-woocommerce.php on line 31

Warning: include_once(includes/FlagshipWoocommerceShipping.php): failed to open stream: No such file or directory in /wp-content/plugins/flagship-for-woocommerce-2.0.17/flagship-for-woocommerce.php on line 43

Warning: include_once(): Failed opening 'includes/FlagshipWoocommerceShipping.php' for inclusion (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') in /wp-content/plugins/flagship-for-woocommerce-2.0.17/flagship-for-woocommerce.php on line 43

Fatal error: Uncaught Error: Class 'FlagshipWoocommerce\FlagshipWoocommerceShipping' not found in /wp-content/plugins/flagship-for-woocommerce-2.0.17/flagship-for-woocommerce.php:47 Stack trace: #0 /wp-settings.php(377): include_once() #1 /wp-config.php(92): require_once('') #2 /public_html/wp-load.php(37): require_once(') #3 /wp-admin/admin.php(34): require_once('') #4 /wp-admin/plugins.php(10): require_once('') #5 {main} thrown in /wp-content/plugins/flagship-for-woocommerce-2.0.17/flagship-for-woocommerce.php on line 47

**Comment by redfishstix** [comment]
While they work out this issue, for people having this issue, revert back to the latest plugin and reinstall it.

1. Move /wp-content/plugins/flagship-for-woocommerce* folder to another name
2. download a fresh copy of the latest working flashship plugin here https://github.com/flagshipcompany/flagship-for-woocommerce/releases/tag/v2.0.22
3. Install it like any other plugins. Your configuration should be unchanged.

**Comment by redfishstix** [comment]
@Red-Cross-Knight Did you try the update for 3.0.1?

**Comment by redfishstix** [comment]
Wordpress is reporting an update version of 3.0.3 but I can only find 3.0.1. I can confirm i'm no longer seeing the issue that we had previously reported. Thanks!

**Comment by Red-Cross-Knight** [comment]
> @Red-Cross-Knight Did you try the update for 3.0.1?

Missed 3.0.1 but had reverted just tried 3.0.3 update and it worked without any issues.

**Comment by radua** [comment]
Please update to version 3.0.5. All reported bugs are fixed in this release
