### ISSUE TITLE
BUG - customers email not being added to tracking 

### ISSUE THREAD

**Issue by Red-Cross-Knight** [flagshipcompany/flagship-for-woocommerce#75]
Customer email isn't being added to the tracking email field when exported from woocommerce.

Running Version 3.0.6
![image](https://user-images.githubusercontent.com/1887734/109703559-99f6d000-7b63-11eb-924d-5a02af3095fc.png)

**Comment by vinhtruong94** [comment]
Hi @Red-Cross-Knight, 
Can you check on your site, Woocommerce > Settings > Shipping > Shipping Zones > Shipping Methods 
Click `Flagship Shipping` and there will be a settings popup. Scroll down and check on the box `Send tracking updates to billing email`. This should include email of customers when you export shipments to Flagship.

**Comment by Red-Cross-Knight** [comment]
We are not using automated quotes because the box sizing doesnt work correctly, and we process dry, live and frozen goods and things never quote properly so we utilize the 'export to flagship' option from the order. 

This used to work fine until a few version ago when it just stopped working. 

It looks like the plugin is relying on shipping zones/methods to get this setting and its not applying to the 'export to flagship' option.

**Comment by vinhtruong94** [comment]
Hi @Red-Cross-Knight,
Yes, the plugin is relying on the shipping zones/methods settings. Can you confirm that the "Send tracking updates to billing email" is checked?
If it's already been checked and the shipment still does not include the tracking emails of the customer then please send the screenshot of the Order Details to [developers@flagshipcompany.com](mailto:developers@flagshipcompany.com)

**Comment by Red-Cross-Knight** [comment]
> Hi @Red-Cross-Knight,
> Yes, the plugin is relying on the shipping zones/methods settings. Can you confirm that the "Send tracking updates to billing email" is checked?
> If it's already been checked and the shipment still does not include the tracking emails of the customer then please send the screenshot of the Order Details to [developers@flagshipcompany.com](mailto:developers@flagshipcompany.com)

Sent an email with more screenshots to help outline the issue.

**Comment by vinhtruong94** [comment]
Hi @Red-Cross-Knight , 
The new version of the plugin is now available on Wordpress. Can you try upload and verify if this issue is fixed ?

**Comment by Red-Cross-Knight** [comment]
> Hi @Red-Cross-Knight ,
> The new version of the plugin is now available on Wordpress. Can you try upload and verify if this issue is fixed ?

Yes it worked, oddly it disabled the plugin and I had to manually reenable it after the upgrade.
