### ISSUE TITLE
BUG: Issue with box sizes post upgrade to Woocommerce 6.3.1

### ISSUE THREAD

**Issue by Red-Cross-Knight** [flagshipcompany/flagship-for-woocommerce#86]
Receiving the following errors when clicking "Export to Flagship" from order screen.

Assuming this is in relation to upgrading to Wordpress 5.9.2 and Woocommerce 6.3.1.

Currently running Flagship version 3.0.15

`FlagShip API Error:

#
Inner length should not be greater than outer length
Inner width should not be greater than outer width
Inner height should not be greater than outer height
Inner length should not be greater than outer length
Inner width should not be greater than outer width
Inner height should not be greater than outer height
Inner length should not be greater than outer length
Inner width should not be greater than outer width
Inner height should not be greater than outer height
Inner length should not be greater than outer length
Inner width should not be greater than outer width
Inner height should not be greater than outer height
Inner length should not be greater than outer length
Inner width should not be greater than outer width
Inner height should not be greater than outer height
Inner length should not be greater than outer length
Inner width should not be greater than outer width
Inner height should not be greater than outer height
Inner length should not be greater than outer length
Inner width should not be greater than outer width
Inner height should not be greater than outer height
Inner length should not be greater than outer length
Inner width should not be greater than outer width
Inner height should not be greater than outer height
Inner length should not be greater than outer length
Inner width should not be greater than outer width
Inner height should not be greater than outer height
Inner length should not be greater than outer length
Inner width should not be greater than outer width
Inner height should not be greater than outer height
Inner length should not be greater than outer length
Inner width should not be greater than outer width
Inner height should not be greater than outer height
Dismiss this notice.
Unable to use FlagShip Packing API. Use fallback weight driven packing.`

**Comment by radua** [comment]
@Red-Cross-Knight Please share a screenshot of your box dimensions

**Comment by Red-Cross-Knight** [comment]
> 

![image](https://user-images.githubusercontent.com/1887734/159391515-dd1ef529-1d77-46da-ad54-8fb70ccce350.png)

**Comment by Red-Cross-Knight** [comment]
Realized I had one that was same inside/outside (2nd last one) fixed that but still same issue:
![image](https://user-images.githubusercontent.com/1887734/159391735-8f351e63-626f-4ab6-8ecd-3cb27f34a509.png)

**Comment by radua** [comment]
@Red-Cross-Knight I tried adding the boxes and was able to do so without any errors. Can you please send a screenshot of all your settings to developers@flagshipcompany.com

**Comment by Red-Cross-Knight** [comment]
> 

Hey Radua, the issues isn't with adding the box sizes, we get this error when we try to export an order to FlagShip via the order page. 

Will send settings later today.

**Comment by Red-Cross-Knight** [comment]
Sorry for delay, emailed screenshots, let me know if you need anything else.
