### ISSUE TITLE
BUG:  Upgrading to WooCommerce 6.6.1 causes Flagship to throw error breaking website

### ISSUE THREAD

**Issue by Red-Cross-Knight** [flagshipcompany/flagship-for-woocommerce#87]
Was testing upgrading WooCommerce to 6.6.1 today, doing so causes the entire site to crash.

Flagship Version 3.0.16 

Error Details
=============
An error of type E_ERROR was caused in line 189 of the file /home/thedrago/public_html/wp-content/plugins/flagship-woocommerce-shipping/src/Injection/Updater/Autoupdate.php. Error message: Uncaught Error: Call to undefined function FS\Injection\Updater\wc() in /home/thedrago/public_html/wp-content/plugins/flagship-woocommerce-shipping/src/Injection/Updater/Autoupdate.php:189
Stack trace:
#0 /home/thedrago/public_html/wp-content/plugins/flagship-woocommerce-shipping/src/Injection/Updater/Autoupdate.php(175): FS\Injection\Updater\Autoupdate->getLatestRelease(Array)
#1 /home/thedrago/public_html/wp-content/plugins/flagship-woocommerce-shipping/src/Injection/Updater/Autoupdate.php(50): FS\Injection\Updater\Autoupdate->resolveRelease()
#2 /home/thedrago/public_html/wp-includes/class-wp-hook.php(309): FS\Injection\Updater\Autoupdate->presetTransient(Object(stdClass))
#3 /home/thedrago/public_html/wp-includes/plugin.php(189): WP_Hook->apply_filters(Object(stdClass), Array)
#4 /home/thedrago/public_html/wp-includes/option.php(1989): apply_filters('pre_set_site_tr...', Object(stdClass), 'update_plugins')
#5 /home/thedrago/public_html/wp-includes/update.php(531): set_site_transient('update_plugins', Obje

**Comment by radua** [comment]
Hi @Red-Cross-Knight I was able to update woocommerce to 6.6.1 and the plugin to 3.0.16. The only error I encountered was a file permissions error. I am not able to reproduce the issue on my end but I'll try and look into it

![image](https://user-images.githubusercontent.com/14368934/176276501-52f0121a-f2c7-4097-9732-ebd1ac8c3046.png)

**Comment by Red-Cross-Knight** [comment]
@radua - I tried to install again and it installed fine and didn't' crash.... ghost in the machine?

**Comment by radua** [comment]
Probably :)
